import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="bg-rafedGray-g5  text-rafedGray-g1 font-Almarai relative">
        {children}
      </body>
    </html>
  );
}
